### ISSUE TITLE
JSON deserialization error when parsing tags that have no content

### ISSUE THREAD

**Issue by bluejorts** [McSib/e621_downloader#39]
The relevant tag in my tags list is `qualzaar`, which is a typo and should be `qualzar`. That said, better behavior for blank tags would be nice, it was not clear that I had made a typo until I double checked a few other things first.

## Trace
```
PS Z:\porn\furry\!! e621 downloader> cmd /C "set RUST_BACKTRACE=full && e621_downloader.exe"
Should enter safe mode? no
thread 'main' panicked at 'Json was unable to deserialize to Vec<AliasEntry>!: reqwest::Error { kind: Decode, source: Error("invalid type: map, expected a sequence", line: 1, column: 0) }', src\e621\sender.rs:762:9
stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace/dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src\libstd\sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src\libstd\sys_common/backtrace.rs:59
   4: core::fmt::write
             at src\libcore\fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src\libstd\io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src\libstd\sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src\libstd\sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src\libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src\libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:511
  11: rust_begin_unwind
             at src\libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src\libcore/panicking.rs:111
  13: core::option::expect_none_failed
             at src\libcore/option.rs:1268
  14: e621_downloader::e621::sender::RequestSender::query_aliases
  15: e621_downloader::e621::io::tag::parse_tag_file
  16: e621_downloader::main
  17: std::rt::lang_start::{{closure}}
  18: std::rt::lang_start_internal::{{closure}}
             at src\libstd/rt.rs:52
  19: std::panicking::try::do_call
             at src\libstd/panicking.rs:331
  20: std::panicking::try
             at src\libstd/panicking.rs:274
  21: std::panic::catch_unwind
             at src\libstd/panic.rs:394
  22: std::rt::lang_start_internal
             at src\libstd/rt.rs:51
  23: main
  24: _tmainCRTStartup
  25: mainCRTStartup
  26: _report_error
  27: _report_error
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Content of tags.txt
```
# This is the tag file that you will use so the program can know what tags to search.
# If you wish to comment in this file, simply put `#` at the beginning or end of line.

# Insert tags you wish to download in the appropriate group (remove all example tags and IDs with what you wish to download):

[artists]
braeburned
funkybun
trigaroo
shoutingisfun
teranen
qualzaar

[pools]
20047 # Funky: Skinny-dip
21826 # Funky: Toy Store
19459 # Funky: Butt Stuff
16713 # Funky: Cafe Expose
13691 # Funky: They won't mind (nude beach)
13818 # female rose alt of above

[sets]

[single-post]

[general]
```

**Comment by McSib** [comment]
This is probably an issue to do with the validator. I actually have a validating system built into the tag class which reads all of the tags from the file and parses it. There's a chance the tag reader is actually panicking when it can't figure out what type of tag the one you put in was. I'mma have to enter in something to make sure that it distinguishes if it's a typo or not. 

There's two section the panic could be coming from:
- Whenever it's trying to figure out what category the tag is, whether the tag is an artist tag, a general tag, a character tag, etc.
- Whenever the tag is being checked for whether or not it's an alias, it could be throwing because of the fact that it uses the tag and searches for an alias without a safeguard, but I'm pretty sure I had a safeguard implemented already. So I'll have to double-check on that whenever I get home. 

This is all I can really say for now, I'm at work and the best I can do is just assume what's going on. There's also another issue I have to handle first, and there's a pull request for it, but I need to validate that it fits within the code properly before I can pull safely.

**Comment by bluejorts** [comment]
No problem at all, this is an edge case and most people are likely never going to enter a tag that has no content associated with it on E6.

**Comment by McSib** [comment]
While it is an edge case, the program should be able to run and handle empty tags as good as tags with post tied to it. So it is sort of a pressing issue when it comes towards the deserializer for JSON.

**Comment by McSib** [comment]
After working a bit, I have fixed a bug that I didn't even know of which made it impossible for the validator to actually notify the user that they had a typo. It pretty much forced the validator to either have a valid tag, or a valid alias and nothing else which is troublesome. This issue is fixed now though, so hopefully everything will work better from here on out.
