### ISSUE TITLE
Failed to save image - System cannot find the path specified.

### ISSUE THREAD

**Issue by Fayetech** [McSib/e621_downloader#58]
Tried to run a DL for freckles_(artist) tag on due to pre-existing freckles tag for obvious reasons. I wound up getting system cannot find the path specified error. I've attached my tags file, as well as config and finally the error file. 
[e621_downloader.log](https://github.com/McSib/e621_downloader/files/9692923/e621_downloader.log)
[tags.txt](https://github.com/McSib/e621_downloader/files/9692924/tags.txt)
[config.txt](https://github.com/McSib/e621_downloader/files/9692925/config.txt)

**Comment by McSib** [comment]
Please refer to issue #59. That is where I'll be posting updates and keeping anything I find there.

**Comment by McSib** [comment]
This bug has been marked as fixed. It was curious, but the moment I saw a space at the end of the collection name, I had a gut feeling about what might've been happening.

The recent commit and branch merge on the develop branch shows the issue more clearly.


![Image](https://user-images.githubusercontent.com/40368716/207076615-937464e7-83bb-4a45-8835-4c79ee79b8f7.png)



![Image](https://user-images.githubusercontent.com/40368716/207076774-3a8d20cd-e6e4-41ca-bb17-2c8848dc5479.png)

The program had a collection name (which turns into the folder name) with a space at the end. This is an invalid name for folders, and the system will ignore creating it. That's why you were getting errors with the path not existing. I still have more to do and more to add before you can get your hands on the fix fully, but my deadline is set for the 31st of December at the latest, so you should be seeing an update soon. Thanks for remaining patient. Have a good day 😄
